const questions = [
  { title: 'Worry about things.', trait: 'N', facet: 1, positive: true },
  { title: 'Make friends easily.', trait: 'E', facet: 1, positive: true },
  { title: 'Have a vivid imagination.', trait: 'O', facet: 1, positive: true },
  { title: 'Trust others.', trait: 'A', facet: 1, positive: true },
  { title: 'Complete tasks successfully.', trait: 'C', facet: 1, positive: true },
  { title: 'Fear for the worst.', trait: 'N', facet: 1, positive: true },
  { title: 'Feel comfortable around people.', trait: 'E', facet: 1, positive: true },
  { title: 'Enjoy wild flights of fantasy.', trait: 'O', facet: 1, positive: true },
  { title: 'Believe that others have good intentions.', trait: 'A', facet: 1, positive: true },
  { title: 'Excel in what I do.', trait: 'C', facet: 1, positive: true },
  { title: 'Am afraid of many things.', trait: 'N', facet: 1, positive: true },
  { title: 'Avoid contacts with others.', trait: 'E', facet: 1, positive: false },
  { title: 'Love to daydream.', trait: 'O', facet: 1, positive: true },
  { title: 'Trust what people say.', trait: 'A', facet: 1, positive: true },
  { title: 'Handle tasks smoothly.', trait: 'C', facet: 1, positive: true },
  { title: 'Get stressed out easily.', trait: 'N', facet: 1, positive: true },
  { title: 'Keep others at a distance.', trait: 'E', facet: 1, positive: false },
  { title: 'Like to get lost in thought.', trait: 'O', facet: 1, positive: true },
  { title: 'Distrust people.', trait: 'A', facet: 1, positive: false },
  { title: 'Know how to get things done.', trait: 'C', facet: 1, positive: true },
  { title: 'Get angry easily.', trait: 'N', facet: 2, positive: true },
  { title: 'Love large parties.', trait: 'E', facet: 2, positive: true },
  { title: 'Believe in the importance of art.', trait: 'O', facet: 2, positive: true },
  { title: 'Use others for my own ends.', trait: 'A', facet: 2, positive: false },
  { title: 'Like to tidy up.', trait: 'C', facet: 2, positive: true },
  { title: 'Get irritated easily.', trait: 'N', facet: 2, positive: true },
  { title: 'Talk to a lot of different people at parties.', trait: 'E', facet: 2, positive: true },
  { title: 'See beauty in things that others might not notice.', trait: 'O', facet: 2, positive: true },
  { title: 'Cheat to get ahead.', trait: 'A', facet: 2, positive: false },
  { title: 'Often forget to put things back in their proper place.', trait: 'C', facet: 2, positive: false },
  { title: 'Lose my temper.', trait: 'N', facet: 2, positive: true },
  { title: 'Prefer to be alone.', trait: 'E', facet: 2, positive: false },
  { title: 'Do not like poetry.', trait: 'O', facet: 2, positive: false },
  { title: 'Take advantage of others.', trait: 'A', facet: 2, positive: false },
  { title: 'Leave a mess in my room.', trait: 'C', facet: 2, positive: false },
  { title: 'Am not easily annoyed', trait: 'N', facet: 2, positive: false },
  { title: 'Avoid crowds.', trait: 'E', facet: 2, positive: false },
  { title: 'Do not enjoy going to art museums.', trait: 'O', facet: 2, positive: false },
  { title: 'Obstruct others plans.', trait: 'A', facet: 2, positive: false },
  { title: 'Leave my belongings around.', trait: 'C', facet: 2, positive: false },
  { title: 'Often feel blue.', trait: 'N', facet: 3, positive: true },
  { title: 'Take charge.', trait: 'E', facet: 3, positive: true },
  { title: 'Experience my emotions intensely.', trait: 'O', facet: 3, positive: true },
  { title: 'Am concerned about others.', trait: 'A', facet: 3, positive: true },
  { title: 'Keep my promises.', trait: 'C', facet: 3, positive: true },
  { title: 'Dislike myself.', trait: 'N', facet: 3, positive: true },
  { title: 'Try to lead others.', trait: 'E', facet: 3, positive: true },
  { title: 'Feel others emotions.', trait: 'O', facet: 3, positive: true },
  { title: 'Love to help others.', trait: 'A', facet: 3, positive: true },
  { title: 'Tell the truth.', trait: 'C', facet: 3, positive: true },
  { title: 'Am often down in the dumps.', trait: 'N', facet: 3, positive: true },
  { title: 'Take control of things.', trait: 'E', facet: 3, positive: true },
  { title: 'Rarely notice my emotional reactions.', trait: 'O', facet: 3, positive: false },
  { title: 'Am indifferent to the feelings of others.', trait: 'A', facet: 3, positive: false },
  { title: 'Break rules.', trait: 'C', facet: 3, positive: false },
  { title: 'Feel comfortable with myself.', trait: 'N', facet: 3, positive: false },
  { title: 'Wait for others to lead the way.', trait: 'E', facet: 3, positive: false },
  { title: 'Dont understand people who get emotional.', trait: 'O', facet: 3, positive: false },
  { title: 'Take no time for others.', trait: 'A', facet: 3, positive: false },
  { title: 'Break my promises.', trait: 'C', facet: 3, positive: false },
  { title: 'Find it difficult to approach others.', trait: 'N', facet: 4, positive: true },
  { title: 'Am always busy.', trait: 'E', facet: 4, positive: true },
  { title: 'Prefer variety to routine.', trait: 'O', facet: 4, positive: true },
  { title: 'Love a good fight.', trait: 'A', facet: 4, positive: false },
  { title: 'Do more than whats expected of me.', trait: 'C', facet: 4, positive: true },
  { title: 'Am afraid to draw attention to myself.', trait: 'N', facet: 4, positive: true },
  { title: 'Am always on the go.', trait: 'E', facet: 4, positive: true },
  { title: 'Prefer to stick with things that I know.', trait: 'O', facet: 4, positive: false },
  { title: 'Yell at people.', trait: 'A', facet: 4, positive: false },
  { title: 'Work hard.', trait: 'C', facet: 4, positive: true },
  { title: 'Only feel comfortable with friends.', trait: 'N', facet: 4, positive: true },
  { title: 'Do a lot in my spare time.', trait: 'E', facet: 4, positive: true },
  { title: 'Dislike changes.', trait: 'O', facet: 4, positive: false },
  { title: 'Insult people.', trait: 'A', facet: 4, positive: false },
  { title: 'Put little time and effort into my work.', trait: 'C', facet: 4, positive: false },
  { title: 'Am not bothered by difficult social situations.', trait: 'N', facet: 4, positive: false },
  { title: 'Like to take it easy.', trait: 'E', facet: 4, positive: false },
  { title: 'Am attached to conventional ways.', trait: 'O', facet: 4, positive: false },
  { title: 'Get back at others.', trait: 'A', facet: 4, positive: false },
  { title: 'Do just enough work to get by.', trait: 'C', facet: 4, positive: false },
  { title: 'Go on binges.', trait: 'N', facet: 5, positive: true },
  { title: 'Love excitement.', trait: 'E', facet: 5, positive: true },
  { title: 'Love to read challenging material.', trait: 'O', facet: 5, positive: true },
  { title: 'Believe that I am better than others.', trait: 'A', facet: 5, positive: false },
  { title: 'Am always prepared.', trait: 'C', facet: 5, positive: true },
  { title: 'Rarely overindulge.', trait: 'N', facet: 5, positive: false },
  { title: 'Seek adventure.', trait: 'E', facet: 5, positive: true },
  { title: 'Avoid philosophical discussions.', trait: 'O', facet: 5, positive: false },
  { title: 'Think highly of myself.', trait: 'A', facet: 5, positive: false },
  { title: 'Carry out my plans.', trait: 'C', facet: 5, positive: true },
  { title: 'Easily resist temptations.', trait: 'N', facet: 5, positive: false },
  { title: 'Enjoy being reckless.', trait: 'E', facet: 5, positive: true },
  { title: 'Have difficulty understanding abstract ideas.', trait: 'O', facet: 5, positive: false },
  { title: 'Have a high opinion of myself.', trait: 'A', facet: 5, positive: false },
  { title: 'Waste my time.', trait: 'C', facet: 5, positive: false },
  { title: 'Am able to control my cravings.', trait: 'N', facet: 5, positive: false },
  { title: 'Act wild and crazy.', trait: 'E', facet: 5, positive: true },
  { title: 'Am not interested in theoretical discussions.', trait: 'O', facet: 5, positive: false },
  { title: 'Boast about my virtues.', trait: 'A', facet: 5, positive: false },
  { title: 'Have difficulty starting tasks.', trait: 'C', facet: 5, positive: false },
  { title: 'Panic easily.', trait: 'N', facet: 6, positive: true },
  { title: 'Radiate joy.', trait: 'E', facet: 6, positive: true },
  { title: 'Tend to vote for liberal political candidates.', trait: 'O', facet: 6, positive: true },
  { title: 'Sympathize with the homeless.', trait: 'A', facet: 6, positive: true },
  { title: 'Jump into things without thinking.', trait: 'C', facet: 6, positive: false },
  { title: 'Become overwhelmed by events.', trait: 'N', facet: 6, positive: true },
  { title: 'Have a lot of fun.', trait: 'E', facet: 6, positive: true },
  { title: 'Believe that there is no absolute right and wrong.', trait: 'O', facet: 6, positive: true },
  { title: 'Feel sympathy for those who are worse off than myself.', trait: 'A', facet: 6, positive: true },
  { title: 'Make rash decisions.', trait: 'C', facet: 6, positive: false },
  { title: 'Feel that Im unable to deal with things.', trait: 'N', facet: 6, positive: true },
  { title: 'Love life.', trait: 'E', facet: 6, positive: true },
  { title: 'Tend to vote for conservative political candidates.', trait: 'O', facet: 6, positive: false },
  { title: 'Am not interested in other peoples problems.', trait: 'A', facet: 6, positive: false },
  { title: 'Rush into things.', trait: 'C', facet: 6, positive: false },
  { title: 'Remain calm under pressure.', trait: 'N', facet: 6, positive: false },
  { title: 'Look at the bright side of life.', trait: 'E', facet: 6, positive: true },
  { title: 'Believe that we should be tough on crime.', trait: 'O', facet: 6, positive: false },
  { title: 'Try not to think about the needy.', trait: 'A', facet: 6, positive: false },
  { title: 'Act without thinking.', trait: 'C', facet: 6, positive: false },
]

export default questions;